export default function Head() {
	return (
		<>
			<title>Next Firebase Auth Template</title>
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1"
			/>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</>
	);
}
